install.packages("rmarkdown")
install.packages("caTools")
install.packages("bitops")

install.packages("ggplot2")
install.packages("formatR")
install.packages("tint")
install.packages("pagedown")
install.packages("bookdown")
install.packages("blogdown")
blogdown::install_hugo()

install.packages("revealjs")
install.packages("tikzDevice")
install.packages("DiagrammeR")
install.packages("DiagrammeRsvg")
install.packages("rsvg")
